### ISSUE TITLE
Override datetimeFilds variable in Timer model

### ISSUE THREAD

**Issue by bryce13950** [PomeloProductions/countdown#14]
This is going to be dependent on Word Wrap version 0.11.0 to be complete https://github.com/PomeloProductions/word-wrap/milestone/3. The datetimeFields added in WordWrap version 0.11.0 needs to be overriden and then the countdown_end_time will need to be added to it.

**Comment by Quixotical** [comment]
so for this ticket, I'm actually sending something to the deprecated field?

**Comment by bryce13950** [comment]
No, you are using the new model variable.

**Comment by Quixotical** [comment]
ok.. so then do I need to change a column in the database? Because right now the field $countdown_end_time is just the name of the column field.. but if it's just going to a generic array of any date_times, how do I have it fill that instead since I only get it from a $timer object which has the table column field countdown_end_time...

**Comment by bryce13950** [comment]
you just need to add a variable to the mode that would be 

`protected $datetimeFields = ["countdown_end_time"];`

**Comment by bryce13950** [comment]
Then $timer->countdown_end_time will be a DateTime object.

**Comment by Quixotical** [comment]
alrighty
